options moal mod_para=nxp/wifi_mod_para.conf

# The onboard SD8978/IW416 (SDIO 02df:9159) has two drivers:
# 1. moal built out of tree in yocto - nxp common driver
# 2. mwifiex inside kernel. - community driver in tree from old mrvl/nxp driver.
# These are two different driver packages for the samething.
# This creates a race condition for the two modules trying to get the chip.
# Blacklist mwifiex here so moal stays the owner on images that install this driver.
# Images without moal - e.g. core-image-bsp - have no moal.conf and let mwifiex bind normally.
blacklist mwifiex_sdio
blacklist mwifiex
